libreria/apps/producto/urls.py
from django.conf.urls import url
from apps.producto.views import index, producto_view, producto_list, producto_edit, producto_delete

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', producto_view, name='producto_crear'),
    url(r'^listar$', producto_list, name='producto_listar'),
    url(r'^editar/(?P<id_producto>\d+)/$', producto_edit, name='producto_editar'),
    url(r'^eliminar/(?P<id_producto>\d+)/$', producto_delete, name='producto_eliminar'),
]

libreria/apps/sendemail/urls.py
# sendemail/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from .views import emailView, successView

urlpatterns = [
    path('email/', emailView, name='email'),
    path('success/', successView, name='success'),
]

libreria/libreria/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.contrib.auth import login
from apps.accounts.views import user_list, deshabilitar_user


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^inicio/', include (('apps.producto.urls', 'producto'), namespace = "producto")),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^userlist/', user_list, name='user_listar'),
    url(r'^user_disable/(?P<username>\d+)/$', deshabilitar_user, name='disable_user'),
    
    url(r'^send/', include (('apps.sendemail.urls', 'sendemail'), namespace = "email")),
]

libreria/apps/producto/models.py
from django.db import models

"""class Tipo(models.Model):
    nombre = models.CharField(max_length = 30)

    def __str__ (self):
        return '{}'.format(self.nombre)
"""
# Create your models here.
class Producto(models.Model):
    nombre = models.CharField(max_length = 40)
    descripcion = models.CharField(max_length = 50)
    precio = models.IntegerField()
    cantidad = models.IntegerField()
    codigo = models.IntegerField()
    tipo = models.CharField(max_length = 40)

    def __str__(self):
        return '{}'.format(self.nombre)

libreria/apps/sendemail/models.py
from django.db import models

# Create your models here.

libreria/apps/producto/forms.py
from django import forms
from apps.producto.models import Producto

class ProductoForm(forms.ModelForm):
    
    class Meta:
        model = Producto

        fields = [
            'nombre',
            'tipo',
            'descripcion',
            'precio',
            'cantidad',
            'codigo',
        ]

        label = {
            'nombre' : 'Nombre',
            'tipo' : 'Tipo',
            'descripcion' : 'Descripción',
            'precio' : 'Precio',
            'cantidad' : 'Cantidad',
            'codigo' : 'Código',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'tipo': forms.TextInput(attrs={'class':'form-control'}),
            'descripcion': forms.TextInput(attrs={'class':'input-field'}),
            'precio': forms.TextInput(attrs={'class':'input-field'}),
            'cantidad': forms.TextInput(attrs={'class':'input-field'}),
            'codigo': forms.TextInput(attrs={'class':'input-field'}),
        }

libreria/apps/sendemail/forms.py
from django import forms

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

libreria/apps/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.core.mail import send_mail
# Create your views here.


def user_list(request):
    user = User.objects.all()
    contexto = {'users':user}
    return render(request, 'registration/user_list.html', contexto)

def deshabilitar_user(request, username):
    user = User.objects.get(username=username)
    user.is_active = False
    user.save()
    messages.success(request, 'Profile successfully disabled.')
    return redirect('index')


def mail(request):
    send_mail('Solicitud de despacho',
    'cuaderno alquimia, hojas oficio',
    'librerialmg@gmail.com',
    ['joc.gutierrezl@alumnos.duoc.cl'],
    fail_silently=False)

    return render(request, 'base/send_email.html')

libreria/apps/producto/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from apps.producto.forms import ProductoForm
from apps.producto.models import Producto
# Create your views here.


def index(request):
    return render(request, 'producto/producto.html')

def producto_view(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('producto:index')
    else:
        form = ProductoForm()
        
    return render(request, 'producto/producto_form.html', {'form':form})

def producto_list(request):
    producto = Producto.objects.all()
    contexto = {'productos':producto}
    return render(request, 'producto/producto_list.html', contexto)

def producto_edit(request, id_producto):
    producto = Producto.objects.get(id=id_producto)
    if request.method == 'GET':
        form = ProductoForm(instance=producto)
    else:
        form = ProductoForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
        return redirect('producto:producto_listar')
    return render(request, 'producto/producto_form.html', {'form':form})

def producto_delete(request, id_producto):
    producto = Producto.objects.get(id=id_producto)
    if request.method == 'POST':
        producto.delete()
        return redirect('producto:producto_listar')
    return render(request, 'producto/producto_delete.html', {'producto':producto})

libreria/apps/sendemail/views.py
# sendemail/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm

def emailView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['panchaguerrerodiaz@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('sendemail:success')
    return render(request, "registration/email.html", {'form': form})

def successView(request):
    return HttpResponse('Tu solicitud de despacho ha sido enviada exitosamente')

libreria/templates/base/base.html
{% load staticfiles %}
{% load materializecss %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>{% block title %}Eliminar de Productos - Librería LMG{% endblock %}</title>
  {% block css %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
{% endblock css %}
  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static '/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static '/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static '/css/materialize.min.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body> 
  <nav class="light orange lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Librería LMG</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">Salir</a></li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="#">Navbar Link></a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  
  {% block content %}

  {% endblock %}
  <footer class="page-footer orange">
    <div class="footer-copyright">
      <div class="container">
       <a class="orange-text text-lighten-3" href="">Librería LMG</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="% static 'js/materialize.js' %"></script>
  <script src="% static 'js/init.js' %"></script>


  {% block javascript %}
<script
src="https://code.jquery.com/jquery-3.3.1.min.js"
integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

<script>
$(document).ready(function(){

// Initialize materialize data picker
$('.datepicker').datepicker({'format': 'yyyy-mm-dd'});
$('select').formSelect();

});

</script>

{% endblock javascript %}
  </body>
</html>

libreria/templates/producto/producto.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Inicio - Librería LMG</title>
  
  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'css/materialize.min.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body> 
  <nav class="light orange lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Librería LMG</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">Salir</a></li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="#">Navbar Link></a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      <h1 class="header center orange-text">Bienvenido!</h1>
      <div class="row center">
        <a href="" id="download-button" class="btn-large waves-effect waves-light orange">Stock de productos</a>
      </div>
      <br><br>
    </div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">assignment</i></h2>
            <h5 class="center">Despacho</h5>

            <p class="light">-Recepcionar <br>-Pedir </p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
            <h5 class="center">Gestión de Usuarios</h5>

            <p class="light">-Agregar <br>-Deshabilitar </p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">view_list</i></h2>
            <a href="{% url 'producto:producto_crear' %}"><h5 class="center">Gestión de Productos</h5> </a> 

            <a href="{% url 'producto:producto_listar' %}">-Listar</a>
            <p class="light">-Agregar <br>-Modificar  <br>-Eliminar</p>
          </div>
        </div>
      </div>

    </div>
    <br><br>
  </div>

  <footer class="page-footer orange">
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="% static 'js/materialize.js' %"></script>
  <script src="% static 'js/init.js' %"></script>

  </body>
</html>

libreria/templates/producto/producto_delete.html
{% extends base/base.html %}
{% load materializecss %}
{% load staticfiles %}

{% block content %}
  
  <div class="container">
    <div class="row center">
        <form method="post">
            {% csrf_token %}
            <h3>¿Desea eliminar el registro de {{ producto.nombre }}?</h3>

            <button class="btn waves-effect waves-light red" type="submit">Sí, eliminar</button>
            <a class="btn waves-effect waves-light blue" href="{% url 'producto:producto_listar' %}">Cancelar</a>
        </form>

    </div>
   <br><br><br>
  </div>

 {% endblock %}

libreria/templates/producto/producto_form.html
{% load staticfiles %}
{% load materializecss %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Registro de Productos - Librería LMG</title>
  {% block css %}
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
  {% endblock css %}
  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'css/materialize.min.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body> 
  <nav class="light orange lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Librería LMG</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">Salir</a></li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="#">Navbar Link></a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  
  <div class="container">
    <form method="post">
            <div class="row ">
                <div class="col s4">
                            
                </div>
                     
                <div class="col s4">
                        {% csrf_token %}
                        {{ form.as_p }}
                        

                </div>
            </div>
        
        
       
        
        <br>

        <div class="row center">

                <button class="btn waves-effect waves-light center" type="submit" name="action">Guardar</button>
    
            </div>
    </form>
  </div>


  {% block javascript %}
<script
src="https://code.jquery.com/jquery-3.3.1.min.js"
integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

<script>
$(document).ready(function(){

// Initialize materialize data picker
$('.datepicker').datepicker({'format': 'yyyy-mm-dd'});
$('select').formSelect();

});

</script>

{% endblock javascript %}
  <footer class="page-footer orange">
    <div class="footer-copyright">
      <div class="container">
       <a class="orange-text text-lighten-3" href="">Librería LMG</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="% static 'js/materialize.js' %"></script>
  <script src="% static 'js/init.js' %"></script>

  </body>
</html>

libreria/templates/producto/producto_list.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Lista de Productos - Librería LMG</title>
  
  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'css/materialize.min.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body> 
  <nav class="light orange lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Librería LMG</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">Salir</a></li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="#">Navbar Link></a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  
  <div class="container">
    <table class="table table-bordered">
        <thead>
            <tr>
                
                <td>Nombre</td>
                <td>Tipo</td>
                <td>Descripcion</td>
                <td>Precio</td>
                <td>Cantidad</td>
                <td>Código</td>
                <td>Acciones</td>
            </tr>
        </thead>
        <tbody>
            {% if productos %}
            {% for producto in productos %}
            <tr>
                
                <td>{{ producto.nombre }}</td>
                <td>{{ producto.tipo }}</td>
                <td>{{ producto.descripcion }}</td>
                <td>$ {{ producto.precio }}</td>
                <td>{{ producto.cantidad }}</td>
                <td>{{ producto.codigo }}</td>
                <td>
                  <a class="btn waves-effect waves-light orange" href="{% url 'producto:producto_editar' producto.id %}">Editar</a>
                  <a class="btn waves-effect waves-light red" href="{% url 'producto:producto_eliminar' producto.id %}">Eliminar</a>
                
                
                </td>
            </tr>
    
            {% endfor %}
    
            {% else %}
    
            <h1>No existen registros</h1>
    
            {% endif %}
        </tbody>
    </table>
   
  </div>

  <footer class="page-footer orange">
    <div class="footer-copyright">
      <div class="container">
       <a class="orange-text text-lighten-3" href="">Librería LMG</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="% static 'js/materialize.js' %"></script>
  <script src="% static 'js/init.js' %"></script>

  </body>
</html>

libreria/templates/producto/producto_no_valido.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Error Agregar Producto - Librería LMG</title>
  
  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static '/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static '/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static '/css/materialize.min.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body> 
  <nav class="light orange lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Librería LMG</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">Salir</a></li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="#">Navbar Link></a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  
  <div class="container">
    <div class="row center">
        <form method="post">
            {% csrf_token %}
            <h3>Datos ingresados son incorrectos</h3>
            <h4>Por favor, intente otra vez</h4>
            <a class="btn waves-effect waves-light blue" href="{% url 'producto:producto_crear' %}">Volver</a>
        </form>

    </div>
   <br><br><br>
  </div>

  <footer class="page-footer orange">
    <div class="footer-copyright">
      <div class="container">
       <a class="orange-text text-lighten-3" href="">Librería LMG</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="% static 'js/materialize.js' %"></script>
  <script src="% static 'js/init.js' %"></script>

  </body>
</html>